--- 
jobs: 
  build: 
    docker: 
      - 
        image: "cypress/base:10"
    steps: 
      - checkout
test1: 
  docker: 
    - 
      environment: 
        TERM: xterm
      image: "cypress/base:10"
  steps: 
    - 
      attach_workspace: 
        at: ~/
    - 
      run: "ls -la cypress"
    - 
      run: "ls -la cypress/integration"
    - 
      run: 
        command: "$(npm bin)/cypress run --spec cypress/integration/sample1.spec.js"
        name: "Running cypress tests 1"
test2: 
  docker: 
    - 
      environment: 
        TERM: xterm
      image: "cypress/base:10"
  steps: 
    - 
      attach_workspace: 
        at: ~/
    - 
      run: "ls -la cypress"
    - 
      run: "ls -la cypress/integration"
    - 
      run: 
        command: "$(npm bin)/cypress run --spec cypress/integration/sample2.spec.js"
        name: "Running cypress tests 1"
version: 2
workflows: 
  build_and_test: 
    jobs: 
      - build
      - 
        test1: 
          requires: 
            - build
      - 
        test2: 
          requires: 
            - build
